### ISSUE TITLE
incorporate changes from other versions of the repo?

### ISSUE THREAD

**Issue by danomatika** [pd-externals/mrpeach#3]
There is at least one other repo for this set of externals. It might be good to check if there are any fixes in these and incorporate them here.

Other repos found:

* <https://github.com/avilleret/mrpeach>

What do you think @avilleret?

**Comment by reduzent** [comment]
I wasn't aware of that repo. Because maintaining the full library was too much and also because I thought smaller, with focus on one subject libraries would make more sense, I split some of mrpeach's externals into their own repos. Namely:
  * binfile
  * midifile
  * osc
  * slip (from slipdec and slipenc)

If everyone agrees, I suggest to put upcoming efforts in those.

**Comment by danomatika** [comment]
Not a bad idea, yeah. I actually pushed a bunch of fixes for the `error()` change to this branch.

**Comment by reduzent** [comment]
Oh, me too, in the separate repositories.

**Comment by umlaeute** [comment]
but then it should be made clear, that https://github.com/pd-externals/mrpeach is deprecated.

**Comment by umlaeute** [comment]
which i guess you already did with bf10ace5634433c1cba00eeaf3b45f9d15d08613...0a3afee

**Comment by reduzent** [comment]
The question is how should we go about the libraries from the Pd-extended period? Back then, it was common to group libraries by author name. Many of those are not actively maintained by their author anymore, for various reasons. Many come with externals that are functionally not related to each other. Some externals might be super-seeded or could easily be replaced by internal objects nowadays. Today, they often are a bunch of bags of still very useful parts and some less useful parts. From a user point of view, but also for a more sustainable maintenance, I think it makes sense to maintain functionally related subsets of those libraries as new libraries.

Since these days libraries are usually installed through Deken, it doesn't hurt having many smaller libraries instead of a few large ones. When I'm searching for 'osc', I'm probably interested in only the objects that do open sound control and not necessarily in everything that is shipped with mrpeach. 

I propose to keep active development into the split-out repositories. IMHO, we still can keep the mrpeach repo online. I would like the devs to agree on where to put efforts and I'm sorry that commits went already to mrpeach _after_ I split some externals away.

**Comment by danomatika** [comment]
I think splitting them is fine. We can also put them into a Github project called "mrpeach" to keep their overall relationship.

**Comment by umlaeute** [comment]
i agree that splitting is fine.

we cannot really create a "mrpeach" project, as the [mrpeach](https://github.com/mrpeach) namespace is already taken (and unlike gitlab, there's no such things as "subgroups" in github), and in any case i think this would only complicate matters for no particular benefit.

**Comment by umlaeute** [comment]
should we use git-modules to somewhat link the child-repos into their grandfather?

(personally i detest git-modules, and would rather not; but others might think differently about it).

othrewise, can we close this?
